


version: '3'

services:
  blockchain-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: blockchain-server
    command: sleep infinity
    networks:
      - my_network

networks:
  my_network: